LRQA-68818
natocesarrego/liferay-portal pull request #1156
Opened 2021-08-05 19:59 UTC by leticiachiu

2021-08-05 19:59 UTC, liferay-forms commented
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

2021-08-05 19:59 UTC, liferay-forms commented
ci:test:sf

2021-08-05 19:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-05 20:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4987/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4987/jenkins-report.html">here</a>.</b></p>

2021-08-05 20:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8f9a7e04daa5c06bdd21a6ae20794348531823fa">8f9a7e04daa5c06bdd21a6ae20794348531823fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/LRQA-68818">LRQA-68818</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/25f9f4260f570a21c62648f5935d8a9c02b4f3b7">25f9f4260f570a21c62648f5935d8a9c02b4f3b7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4987/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4987/jenkins-report.html">here</a>.</h5></details></html>

2021-08-05 20:03 UTC, liferay-forms commented
ci:test:relevant

2021-08-05 20:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4987/">test-portal-source-format#4987</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4987/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1156">natocesarrego#1156</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551721362">[master] ci:test:sf - leticiachiu &gt; natocesarrego - PR#1156 - 2021-08-05[13:00:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/1610/">publish-testray-report#1610</a><br/></div></div>

2021-08-05 20:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/129/">test-portal-acceptance-pullrequest(master)#129</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/129/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1156">natocesarrego#1156</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551724930">[master] ci:test:relevant - leticiachiu &gt; natocesarrego - PR#1156 - 2021-08-05[13:03:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/369/">publish-testray-report#369</a><br/></div></div>

2021-08-06 13:02 UTC, natocesarrego requested changes
Good pull! Please see my comments below. :wink:

2021-08-06 13:02 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/forms/Form.path
> +	<td>//input[contains(@class,'page-header-title') and @value='${key_formPageName}']/../../../../..//button[contains(@class,'page-button') and @class='reorder-page-button btn btn-monospaced btn-sm btn
@leticiachiu, do you think that we can look for the class `reorder-page-button` only at the end of this path?

The other CSS classes aren't maintained by our team, hence they're not under our control which can make the developers from our team remove them in the future due to changes introduced by who maintain them. Verifying only the class `reorder-page-button` can be a good solution in the long term. :slightly_smiling_face:

2021-08-06 13:02 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/forms/Form.path
> +	<td>//input[contains(@class,'page-header-title') and @value='${key_formPageName}']/../../../../..//button[contains(@class,'page-button') and @class='reorder-page-button btn btn-monospaced btn-sm btn
@leticiachiu, do you think that we can look for the class `reorder-page-button` only at the end of this path?

The other CSS classes aren't maintained by our team, hence they're not under our control which can make the developers from our team remove them in the future due to changes introduced by who maintain them. Verifying only the class `reorder-page-button` can be a good solution in the long term. :slightly_smiling_face:

2021-08-06 18:20 UTC, leticiachiu commented
@natocesarrego fixed

2021-08-09 20:21 UTC, natocesarrego commented
ci:forward

2021-08-09 20:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-09 20:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/155/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/155/jenkins-report.html">here</a>.</b></p>

2021-08-09 20:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f1bfcd8064f37d92d95321c73874c98f80a6b344">f1bfcd8064f37d92d95321c73874c98f80a6b344</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/LRQA-68818">LRQA-68818</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/acef8857305552bd0fc0cc984f69a585690a210b">acef8857305552bd0fc0cc984f69a585690a210b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/155/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/155/jenkins-report.html">here</a>.</h5></details></html>

2021-08-09 20:24 UTC, liferay-forms commented
ci:test:relevant

2021-08-09 20:24 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/test-portal-source-format/155//consoleFull)

2021-08-09 20:24 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105284
[Console](https://test-1-29.liferay.com/job/test-portal-source-format/155//consoleFull)

2021-08-09 20:24 UTC, closed without merging

2021-08-09 20:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/68/">test-portal-acceptance-pullrequest(master)#68</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/68/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1156">natocesarrego#1156</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552327671">[master] ci:test:relevant - leticiachiu &gt; natocesarrego - PR#1156 - 2021-08-09[13:21:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/186/">publish-testray-report#186</a><br/></div></div>

2021-08-09 21:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/155/">test-portal-source-format#155</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/155/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1156">natocesarrego#1156</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552342808">[master] ci:test:sf - leticiachiu &gt; natocesarrego - PR#1156 - 2021-08-09[13:21:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/517/">publish-testray-report#517</a><br/></div></div>

2021-08-09 21:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/178/">test-portal-acceptance-pullrequest(master)#178</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/178/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1156">natocesarrego#1156</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552342933">[master] ci:test:relevant - leticiachiu &gt; natocesarrego - PR#1156 - 2021-08-09[13:24:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/518/">publish-testray-report#518</a><br/></div></div>