LPS-185518 Create a SF check for replace with searchContainer.setResultsAndTotal
natocesarrego/liferay-portal pull request #1255
Opened 2023-05-30 13:14 UTC by TamyrisTorres

https://issues.liferay.com/browse/LPS-185518

2023-05-30 13:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-30 13:16 UTC, TamyrisTorres commented
ci:test:sf

2023-05-30 13:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 22 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2db316bbff536551431a9e6bc3f20ca93183c55">d2db316bbff536551431a9e6bc3f20ca93183c55</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-185518">LPS-185518</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2">0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5057/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5057/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl expected:&lt;...?uncap_first + "Id"][ /&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;
     [java]                       else \{
     [java]                         \$\{postBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=postBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java] 
     [java]                         );
     [java]                       \}
     [java]                     &lt;/#if&gt;
     [java]                   &lt;/#if&gt;
     [java] 
     [java]                   &lt;#if postAssetLibraryBatchJavaMethodSignature??&gt;
     [java]                     &lt;#assign parentParameterNames = parentParameterNames + ["assetLibraryId"] ]/&gt;
     [java] 
     [java]                     &lt;#if p...&gt; but was:&lt;...?uncap_first + "Id"][/&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;</pre></details></html>

2023-05-30 13:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5057/">test-portal-source-format#5057</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5057/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1255">natocesarrego#1255</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2324485406">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1255 - 2023-05-30[06:17:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18878/">publish-testray-report#18878</a><br/></div></div>

2023-05-30 13:55 UTC, TamyrisTorres commented
ci:test:sf

2023-05-30 13:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6998/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6998/jenkins-report.html">here</a>.</b></p>

2023-05-30 14:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2db316bbff536551431a9e6bc3f20ca93183c55">d2db316bbff536551431a9e6bc3f20ca93183c55</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-185518">LPS-185518</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2">0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6998/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6998/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl expected:&lt;...?uncap_first + "Id"][ /&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;
     [java]                       else \{
     [java]                         \$\{postBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=postBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java] 
     [java]                         );
     [java]                       \}
     [java]                     &lt;/#if&gt;
     [java]                   &lt;/#if&gt;
     [java] 
     [java]                   &lt;#if postAssetLibraryBatchJavaMethodSignature??&gt;
     [java]                     &lt;#assign parentParameterNames = parentParameterNames + ["assetLibraryId"] ]/&gt;
     [java] 
     [java]                     &lt;#if p...&gt; but was:&lt;...?uncap_first + "Id"][/&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;</pre></details></html>

2023-05-30 14:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6998/">test-portal-source-format#6998</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6998/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1255">natocesarrego#1255</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2324537524">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1255 - 2023-05-30[06:55:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/3997/">publish-testray-report#3997</a><br/></div></div>

2023-05-30 14:49 UTC, nicolas-sss commented
ci:test:sf

2023-05-30 14:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2980/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2980/jenkins-report.html">here</a>.</b></p>

2023-05-30 15:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2db316bbff536551431a9e6bc3f20ca93183c55">d2db316bbff536551431a9e6bc3f20ca93183c55</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-185518">LPS-185518</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2">0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2980/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2980/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl expected:&lt;...?uncap_first + "Id"][ /&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;
     [java]                       else \{
     [java]                         \$\{postBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=postBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java] 
     [java]                         );
     [java]                       \}
     [java]                     &lt;/#if&gt;
     [java]                   &lt;/#if&gt;
     [java] 
     [java]                   &lt;#if postAssetLibraryBatchJavaMethodSignature??&gt;
     [java]                     &lt;#assign parentParameterNames = parentParameterNames + ["assetLibraryId"] ]/&gt;
     [java] 
     [java]                     &lt;#if p...&gt; but was:&lt;...?uncap_first + "Id"][/&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;</pre></details></html>

2023-05-30 15:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7317/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7317/jenkins-report.html">here</a>.</b></p>

2023-05-30 19:14 UTC, nicolas-sss commented
ci:test:sf

2023-05-30 19:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4975/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4975/jenkins-report.html">here</a>.</b></p>

2023-05-30 19:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7317/">test-portal-acceptance-pullrequest(master)#7317</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7317/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1255">natocesarrego#1255</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2324813792">[master] ci:test:relevant - TamyrisTorres &gt; natocesarrego - PR#1255 - 2023-05-30[08:25:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/16929/">publish-testray-report#16929</a><br/></div></div>

2023-05-30 19:35 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/125a112452daa3d47caa5acc0e87d767f30ab4dc">125a112452daa3d47caa5acc0e87d767f30ab4dc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-185518">LPS-185518</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2">0e7fbcdb55762b81688d2ccf3ee66ddcd49960b2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4975/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4975/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl expected:&lt;...?uncap_first + "Id"][ /&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;
     [java]                       else \{
     [java]                         \$\{postBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=postBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java] 
     [java]                         );
     [java]                       \}
     [java]                     &lt;/#if&gt;
     [java]                   &lt;/#if&gt;
     [java] 
     [java]                   &lt;#if postAssetLibraryBatchJavaMethodSignature??&gt;
     [java]                     &lt;#assign parentParameterNames = parentParameterNames + ["assetLibraryId"] ]/&gt;
     [java] 
     [java]                     &lt;#if p...&gt; but was:&lt;...?uncap_first + "Id"][/&gt;
     [java] 
     [java]                       if (parameters.containsKey("\$\{parentBatchJavaMethodSignature.parentSchemaName?uncap_first\}Id")) \{
     [java]                         \$\{parentBatchJavaMethodSignature.methodName\}(
     [java] 
     [java]                         &lt;@getPOSTBatchJavaMethodParameters
     [java]                           javaMethodParameters=parentBatchJavaMethodSignature.javaMethodParameters
     [java]                           schemaVarName=schemaVarName
     [java]                         /&gt;
     [java]                         );
     [java] 
     [java]                       \}
     [java]                       &lt;#if parentBatchJavaMethodSignature?has_next&gt;
     [java]                         else
     [java]                       &lt;/#if&gt;
     [java]                     &lt;/#list&gt;
     [java] 
     [java]                     &lt;#if postBatchJavaMethodSignature??&gt;</pre></details></html>

2023-05-30 19:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4975/">test-portal-source-format#4975</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4975/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1255">natocesarrego#1255</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2324858323">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1255 - 2023-05-30[12:14:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3548/">publish-testray-report#3548</a><br/></div></div>

2023-05-31 13:19 UTC, natocesarrego requested changes

2023-05-31 13:19 UTC, natocesarrego commented on modules/util/source-formatter/src/main/resources/sourcechecks.xml
> +			<description name="Run code migration of metodh searchContainer.setResults to the searchContainer.setResultsAndTotal and delete searchContainer.setTotal" />
@TamyrisTorres, please fix the spelling of the method `method`

2023-05-31 13:38 UTC, nicolas-sss commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsAndTotalCheck.java
> +		}
The content will never be null and about the extension, probably.

2023-06-01 12:20 UTC, TamyrisTorres commented
ci:test:sf

2023-06-01 12:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4986/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4986/jenkins-report.html">here</a>.</b></p>

2023-06-01 12:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4986/">test-portal-source-format#4986</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4986/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1255">natocesarrego#1255</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2327754596">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1255 - 2023-06-01[05:21:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3558/">publish-testray-report#3558</a><br/></div></div>

2023-06-01 12:51 UTC, TamyrisTorres commented
ci:test:relevant

2023-06-01 12:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1245/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1245/jenkins-report.html">here</a>.</b></p>

2023-06-01 14:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 29 out of 29 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 57 out of 58 jobs passed in 1 hour 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d3cf7b928ddefe98e4120138bb2f778caba664">b5d3cf7b928ddefe98e4120138bb2f778caba664</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/23931ddb4c0ca8c744f209c90dd21552440f1e62">23931ddb4c0ca8c744f209c90dd21552440f1e62</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2327635271">EE Development Acceptance (master) - 4575 - 2023-06-01[00:34:13]</a></p><details><summary><strong>ci:test:stable - 29 out of 29 jobs PASSED</strong></summary><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 56 out of 58 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1245/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206950/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539638/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/199916/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/220799/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539637/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522002/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213874/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539639/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/414441/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213871/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/544372/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/212913/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/563283/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203962/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/513553/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225138/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201042/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215945/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/504781/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/654444/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/594997/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128062/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200421/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545257/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562757/">functional-upgrade-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>lpkg-controller-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/590017/">lpkg-controller-mysql57-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208433/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545255/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200967/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/504775/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/199915/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/522001/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562754/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/513550/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208434/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203961/">modules-compile-jdk8/0/9</a></li><li><a href="http [...]

2023-06-01 14:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1245/">test-portal-acceptance-pullrequest(master)#1245</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1245/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1255">natocesarrego#1255</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2327824911">[master] ci:test:relevant - TamyrisTorres &gt; natocesarrego - PR#1255 - 2023-06-01[05:51:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2494/">publish-testray-report#2494</a><br/></div></div>

2023-06-01 19:32 UTC, natocesarrego requested changes

2023-06-01 19:32 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsAndTotalCheck.java
> +		}
@TamyrisTorres, based on what @nicolas-sss said, can you please remove the check `(content == null)`?

Thanks

2023-06-01 19:32 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsAndTotalCheck.java
> +		String methodCall, String className, String content) {
@TamyrisTorres, please sort the parameters according alphabetic order

2023-06-01 19:32 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsAndTotalCheck.java
> +		String variableDeclaration = getVariableTypeName(
@TamyrisTorres, please rename `variableDeclaration` to `variableTypeName` to keep consistency. I mean, the method is named `getVariableTypeName`, therefore we should name the variable receiving the return of this function accordingly. :wink:

2023-06-01 19:32 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsAndTotalCheck.java
> +	private boolean _validateClassName(
@TamyrisTorres, please rename the method to `_hasClassName`

2023-06-01 19:32 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsAndTotalCheck.java
> +					content, "\t\t" + methodCall);
@TamyrisTorres, do we really need the `\t\t`? Not necessarily it will always exist in the customer's code, right?

2023-06-01 19:32 UTC, natocesarrego commented on modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/upgrade/UpgradeJavaSetResultsAndTotalCheck.testjava
> +		this.keywords, this.status)).intValue());
@TamyrisTorres, please format according Liferay SF pattern. I mean, use tab, blank line accordingly, etc

Tip: run `gw formatSource` on this code

2023-06-01 19:32 UTC, closed without merging