LPS-188828
natocesarrego/liferay-portal pull request #1295
Opened 2023-06-29 12:43 UTC by TamyrisTorres

LPS-188828

2023-06-29 12:44 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-29 12:45 UTC, TamyrisTorres commented
ci:test:sf

2023-06-29 12:45 UTC, TamyrisTorres commented
ci:test:relevant

2023-06-29 12:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1684/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1684/jenkins-report.html">here</a>.</b></p>

2023-06-29 13:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/857/">test-portal-source-format#857</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/857/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1295">natocesarrego#1295</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2364928802">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1295 - 2023-06-29[05:47:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3336/">publish-testray-report#3336</a><br/></div></div>

2023-06-29 15:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 32 out of 32 jobs passed</h3><h3>:x: ci:test:relevant - 62 out of 65 jobs passed in 2 hours 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/99262f8fa6714886eca405ef5e0e5c407327e194">99262f8fa6714886eca405ef5e0e5c407327e194</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/99262f8fa6714886eca405ef5e0e5c407327e194">99262f8fa6714886eca405ef5e0e5c407327e194</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2364878207">EE Development Acceptance (master) - 4658 - 2023-06-29[00:38:12]</a></p><details><summary><strong>ci:test:stable - 32 out of 32 jobs PASSED</strong></summary><details><summary><strong>32 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 62 out of 65 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1684/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/623749/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611291/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/238501/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231362/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642573/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206869/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240716/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228572/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/681716/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642570/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/219681/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/245391/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/585156/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462197/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240717/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611290/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554074/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229678/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/556637/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231361/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462196/">functional-upgrade-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218911/">functional-upgrade-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206871/">functional-upgrade-tomcat90-mysql57-jdk8/0/9</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545071/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181136/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/585155/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/681720/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215151/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/197875/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>functional-upgrade-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/457760/">functional-upgrade-tomcat90-postgresql144-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545072/">functional-upgrade-tomcat90-postgresql144-jdk8/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/582940/">js-unit-jdk8/0/0</a></li></ul></li><li>lpkg-controller-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545070/"><strike>lpkg-controller-mysql57-jdk8/0/0</strike></a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545069/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/585153/">modules-comp [...]

2023-06-29 15:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1684/">test-portal-acceptance-pullrequest(master)#1684</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1684/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1295">natocesarrego#1295</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365018215">[master] ci:test:relevant - TamyrisTorres &gt; natocesarrego - PR#1295 - 2023-06-29[05:52:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3342/">publish-testray-report#3342</a><br/></div></div>

2023-06-29 18:33 UTC, natocesarrego requested changes

2023-06-29 18:33 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaAddLayoutParameterCheck.java
> +				String newMethod = _toAssembleMethod(
@TamyrisTorres, let's rename to `addMethodNewParameter`

2023-06-29 18:33 UTC, natocesarrego commented on modules/util/source-formatter/src/main/resources/sourcechecks.xml
> +			<description name="Fill the new parameter of the method `addLayout` of `LayoutLocalService`, and `LayoutLocalServiceUtil` classes" />
@TamyrisTorres, no comma needed after `LayoutLocalService` :wink:

2023-06-29 18:33 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/BaseSourceCheck.java
> +		String methodCall) {
@TamyrisTorres, should we just include this new parameter or does make sense we keep the method as it's, I mean, with 3 parameters, and create a new one? What do you think about it?

2023-07-06 12:22 UTC, TamyrisTorres commented
ci:test:sf

2023-07-06 12:22 UTC, TamyrisTorres commented
ci:test:relevant

2023-07-06 12:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3991/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3991/jenkins-report.html">here</a>.</b></p>

2023-07-06 12:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2022/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2022/jenkins-report.html">here</a>.</b></p>

2023-07-06 12:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5363ba79d6f5607b99bc803ceb6c7b50ff779058">5363ba79d6f5607b99bc803ceb6c7b50ff779058</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-188828">LPS-188828</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/924041588d2c872c1a4c61154eabf20f195f3d8a">924041588d2c872c1a4c61154eabf20f195f3d8a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2022/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2022/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 158 formatting issues:
     [java] 1: ./modules/apps/account/account-test/src/testFunctional/macros/json/accountRole/JSONAccountRoleAPI.macro expected:&lt;definition \{
     [java] 
     [java]   [macro _associateUser \{
     [java]     Variables.assertDefined(parameterList = "\$\{accountEntryId\},\$\{accountRoleId\},\$\{userId\}");
     [java] 
     [java]     var portalURL = JSONCompany.getPortalURL();
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/api/jsonws/account.accountrole/associate-user \
     [java]         -u [REDACTED]:test \
     [java]         -d accountEntryId=\$\{accountEntryId\}
     [java]         -d accountRoleId=\$\{accountRoleId\}
     [java]         -d userId=\$\{userId\} \
     [java]     ''';
     [java] 
     [java]     com.liferay.poshi.runner.util.JSONCurlUtil.post(\$\{curl\});
     [java]   \}
     [java] ]
     [java]   macro _getAccountR...&gt; but was:&lt;definition \{
     [java] 
     [java]   [@summary = "Helper function to assign an existing user to an account role"
     [java]   macro _associateUser \{
     [java]     Variables.assertDefined(parameterList = "\$\{accountEntryId\},\$\{accountRoleId\},\$\{userId\}");
     [java] 
     [java]     var portalURL = JSONCompany.getPortalURL();
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/api/jsonws/account.accountrole/associate-user \
     [java]         -u [REDACTED]:test \
     [java]         -d accountEntryId=\$\{accountEntryId\}
     [java]         -d accountRoleId=\$\{accountRoleId\}
     [java]         -d userId=\$\{userId\} \
     [java]     ''';
     [java] 
     [java]     com.liferay.poshi.runner.util.JSONCurlUtil.post(\$\{curl\});
     [java]   \}
     [java] 
     [java]   @summary = "Get the accountRoleId of an account role by using its roleId"]
     [java]   macro _getAccountR...&gt;
     [java] 2: ./modules/apps/account/account-test/src/testFunctional/macros/json/accountRole/JSONAccountRole.macro expected:&lt;definition \{
     [java] 
     [java]   []macro associateUser ...&gt; but was:&lt;definition \{
     [java] 
     [java]   [@summary = "Directly calls the JSON WS API to assign an account role to an existing user"
     [java]   ]macro associateUser ...&gt;
     [java] 3: ./modules/apps/account/account-test/src/testFunctional/macros/json/accountEntry/JSONAccountEntryAPI.macro expected:&lt;...post(\$\{curl\});
     [java]   \}
     [java] 
     [java]   [macro _deleteAllAccountEntries \{
     [java]     if (!(isSet(creatorEmailAddress))) \{
     [java]       var creatorEmailAddress = "[REDACTED]";</pre></details></html>

2023-07-06 12:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2022/">test-portal-source-format#2022</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2022/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1295">natocesarrego#1295</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2372651988">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1295 - 2023-07-06[05:22:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/8295/">publish-testray-report#8295</a><br/></div></div>

2023-07-06 13:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3991/">test-portal-acceptance-pullrequest(master)#3991</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3991/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1295">natocesarrego#1295</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2373000783">[master] ci:test:relevant - TamyrisTorres &gt; natocesarrego - PR#1295 - 2023-07-06[05:22:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/7338/">publish-testray-report#7338</a><br/></div></div>

2023-07-07 18:58 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaAddLayoutParameterCheck.java
> +			}
All good with this pull request, @TamyrisTorres. I just have one last question to you: if tomorrow a new method with 17 parameters too is added to the classes `LayoutLocalService` and `LayoutLocalServiceUtil`, how this check will handle it? Will it be able to distinguish the 2 methods?

2023-07-13 11:33 UTC, natocesarrego approved these changes

2023-07-13 11:33 UTC, natocesarrego commented
Good job, @TamyrisTorres! :smile:

2023-07-19 15:33 UTC, natocesarrego approved these changes

2023-07-19 15:37 UTC, natocesarrego commented
Forwarded to Nícolas: https://github.com/nicolas-sss/liferay-portal/pull/47

2023-07-19 15:37 UTC, closed without merging