LPS-186927
natocesarrego/liferay-portal pull request #1331
Opened 2023-07-20 20:23 UTC by michaelmdelcavalcanti

2023-07-20 20:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-20 20:25 UTC, michaelmdelcavalcanti commented
ci:test:sf

2023-07-20 20:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/2207/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2207/jenkins-report.html">here</a>.</b></p>

2023-07-20 20:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2219c643b32df66e39e7ce5b3abc410e23f3b669">2219c643b32df66e39e7ce5b3abc410e23f3b669</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/michaelmdelcavalcanti/liferay-portal/tree/LPS-186927">LPS-186927</a><br/>Branch GIT ID: <a href="https://github.com/michaelmdelcavalcanti/liferay-portal/commit/68373b5131ac54f1967b79478d2d775228877f61">68373b5131ac54f1967b79478d2d775228877f61</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2207/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2207/jenkins-report.html">here</a>.</h5></details></html>

2023-07-20 20:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2207/">test-portal-source-format#2207</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2207/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1331">natocesarrego#1331</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2390545196">[master] ci:test:sf - michaelmdelcavalcanti &gt; natocesarrego - PR#1331 - 2023-07-20[13:25:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/8069/">publish-testray-report#8069</a><br/></div></div>

2023-07-21 19:17 UTC, natocesarrego requested changes

2023-07-21 19:17 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/JavaUpgradeFetchCPDefinitionByCProductExternalReferenceCodeCheck.java
> +		String javaTermContent = javaTerm.getContent();
@michaelmdelcavalcanti, let's keep the consistency:
```
List<String> importNames = javaTerm.getImportNames();

String content = javaTerm.getContent();
```
or
```
List<String> javaTermImportNames = javaTerm.getImportNames();

String javaTermContent = javaTerm.getContent();
```
Honestly, I'd pick the first option due to simplicity :wink:

2023-07-21 19:17 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/JavaUpgradeFetchCPDefinitionByCProductExternalReferenceCodeCheck.java
> +			content, fileContent, parameterList.get(1));
@michaelmdelcavalcanti, consistency
```
String variableTypeName = getVariableTypeName
```

2023-07-24 16:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5134/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5134/jenkins-report.html">here</a>.</b></p>

2023-07-24 17:00 UTC, natocesarrego approved these changes

2023-07-24 17:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5134/">test-portal-source-format#5134</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5134/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1331">natocesarrego#1331</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2393510915">[master] ci:test:sf - michaelmdelcavalcanti &gt; natocesarrego - PR#1331 - 2023-07-24[09:41:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3781/">publish-testray-report#3781</a><br/></div></div>

2023-07-24 17:05 UTC, closed without merging