LPS-198272
natocesarrego/liferay-portal pull request #1383
Opened 2023-10-09 14:06 UTC by TamyrisTorres

LPS-198272

2023-10-09 14:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-09 14:06 UTC, TamyrisTorres commented
ci:test:sf

2023-10-09 14:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2296/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2296/jenkins-report.html">here</a>.</b></p>

2023-10-09 14:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9ef5643aedadf52524e02d08b1a4aa0163491f9b">9ef5643aedadf52524e02d08b1a4aa0163491f9b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-198272">LPS-198272</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/90a34a73c26bb8ab343a908a82e2dbea7558dc64">90a34a73c26bb8ab343a908a82e2dbea7558dc64</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2296/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2296/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:44)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1298)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:326)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 4:57.185 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:456: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-33/job/test-portal-source-format/2296//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20231009071411904.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20231009071411904.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1534414700.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1539366772
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 200ms
[junitreport] Deleting: /tmp/null1539366772
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-09-2023 07:14:14:813 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2023-10-09 14:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2296/">test-portal-source-format#2296</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2296/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1383">natocesarrego#1383</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2438431926">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1383 - 2023-10-09[07:07:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/9798/">publish-testray-report#9798</a><br/></div></div>

2023-10-10 14:52 UTC, natocesarrego requested changes

2023-10-10 14:56 UTC, natocesarrego commented
Great job, @TamyrisTorres!

I'm really proud of your growing hear at Hotel Team. :smile:

2023-10-10 16:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6711/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6711/jenkins-report.html">here</a>.</b></p>

2023-10-10 17:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6711/">test-portal-source-format#6711</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6711/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1383">natocesarrego#1383</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2439311447">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1383 - 2023-10-10[09:54:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/26418/">publish-testray-report#26418</a><br/></div></div>

2023-10-11 11:40 UTC, natocesarrego approved these changes

2023-10-11 11:56 UTC, natocesarrego commented
Manually forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/142096

2023-10-11 11:56 UTC, closed without merging