LPS-200168
natocesarrego/liferay-portal pull request #1407
Opened 2023-11-08 15:08 UTC by MicaelleSilvaa

2023-11-08 15:08 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-08 16:51 UTC, natocesarrego requested changes

2023-11-08 16:51 UTC, natocesarrego commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +			"AssetCategoryLocalServiceUtil"
@MicaelleSilvaa, can we also include here the `AssetCategoryService` and `AssetCategoryServiceUtil`?

If these classes exist in `master` and also have the methods mentioned in `from` and `to` then it makes sense we include them. From now on, if it's applicable, we should always use, for these specific cases, the following classes:

- `*LocalService`
- `*LocalServiceUtil`
- `*Service`
- `*ServiceUtil`

2023-11-10 11:11 UTC, natocesarrego commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +			"AssetCategoryLocalServiceUtil"
@MicaelleSilvaa, do you have any update about this comment?

Thanks

2023-11-13 16:31 UTC, MicaelleSilvaa commented
ci:test:sf

2023-11-13 16:32 UTC, MicaelleSilvaa commented
ci:test:hotel

2023-11-13 17:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5166/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5166/jenkins-report.html">here</a>.</b></p>

2023-11-14 11:07 UTC, natocesarrego commented
Any update regarding my [previous comment](https://github.com/natocesarrego/liferay-portal/pull/1407#discussion_r1386926142), @MicaelleSilvaa?

Thanks

2023-11-14 18:38 UTC, natocesarrego commented
Please fix conflicts and resend

2023-11-14 18:38 UTC, closed without merging