LPS-200552
natocesarrego/liferay-portal pull request #1414
Opened 2023-11-14 19:25 UTC by TamyrisTorres

Ticket:https://liferay.atlassian.net/browse/LPS-200552

2023-11-14 19:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-14 19:28 UTC, TamyrisTorres commented
ci:test:sf

2023-11-14 19:28 UTC, TamyrisTorres commented
ci:test:hotel

2023-11-14 20:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 36 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4fc9a18bd48612ada94911e0346b22239ed1dd81">4fc9a18bd48612ada94911e0346b22239ed1dd81</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-200552">LPS-200552</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/bc8eaa16539564a3d247b7c928a26c2e7aeca1c3">bc8eaa16539564a3d247b7c928a26c2e7aeca1c3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6370/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6370/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Variable '_log' is unused: ./modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/manager/LayoutLockManagerImpl.java 507 (Checkstyle:UnusedVariableCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)
[stopwatch] [run.batch.test.action: 33:00.194 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:456: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-8/job/test-portal-source-format/6370//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20231114120443188.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20231114120443188.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1962615829.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null623333036
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 188ms
[junitreport] Deleting: /tmp/null623333036
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 11-14-2023 12:04:47:569 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1962615829.properties

print-gc-logs:
     [echo] 
     [echo] ##
     [echo] ## /tmp/ant-gc.log
     [echo] ##
     [echo] 
[beanshell] Java HotSpot(TM) 64-Bit Server VM (25.381-b09) for linux-amd64 JRE (1.8.0_381-b09), built on Jun 14 2023 13:47:37 by "java_re" with gcc 7.3.0</pre></details></html>

2023-11-14 20:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6370/">test-portal-source-format#6370</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6370/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1414">natocesarrego#1414</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2459232109">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1414 - 2023-11-14[11:29:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/4051/">publish-testray-report#4051</a><br/></div></div>

2023-11-14 20:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8661/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8661/jenkins-report.html">here</a>.</b></p>

2023-11-14 22:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 2 hours 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4fc9a18bd48612ada94911e0346b22239ed1dd81">4fc9a18bd48612ada94911e0346b22239ed1dd81</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/279f47dc0637dce38a1fcc48f0ef9c9c969635a3">279f47dc0637dce38a1fcc48f0ef9c9c969635a3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2459063807">EE Development Acceptance (master) - 150 - 2023-11-14[04:42:57]</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8661/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347259/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8661/jenkins-report.html">here</a>.</h5></details></html>

2023-11-14 23:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8661/">test-portal-acceptance-pullrequest(master)#8661</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8661/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1414">natocesarrego#1414</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2459329409">[master] ci:test:hotel - TamyrisTorres &gt; natocesarrego - PR#1414 - 2023-11-14[12:20:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19243/">publish-testray-report#19243</a><br/></div></div>

2023-11-16 11:54 UTC, natocesarrego requested changes

2023-11-16 11:54 UTC, natocesarrego commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeSCSSNodeSassPatternsCheck.java
> +			for (String variableName : interpolations) {
@TamyrisTorres, consistency:
```
String[] interpolationParts = interpolation.split("((\\#\\{)|(\\}))");

for (String interpolationPart : interpolationParts) {
```

2023-11-16 12:40 UTC, TamyrisTorres commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeSCSSNodeSassPatternsCheck.java
> +			for (String variableName : interpolations) {
Resolved

2023-11-20 13:45 UTC, natocesarrego approved these changes

2023-11-20 13:45 UTC, natocesarrego commented
ci:test:sf

2023-11-20 13:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6640/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6640/jenkins-report.html">here</a>.</b></p>

2023-11-20 14:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-200552">LPS-200552</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/35db45f2dfc1f51d97dbcf1bf9fdc5a8ce8ff1e5">35db45f2dfc1f51d97dbcf1bf9fdc5a8ce8ff1e5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6640/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6640/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 14:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6640/">test-portal-source-format#6640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1414">natocesarrego#1414</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462141447">[master] ci:test:sf - TamyrisTorres &gt; natocesarrego - PR#1414 - 2023-11-20[05:47:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3620/">publish-testray-report#3620</a><br/></div></div>

2023-11-20 16:31 UTC, TamyrisTorres commented
ci:test:hotel

2023-11-20 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4512/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4512/jenkins-report.html">here</a>.</b></p>

2023-11-20 19:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 1 hour 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/977b899d04df122a3f482009ee162404729384cb">977b899d04df122a3f482009ee162404729384cb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/263958bba46acbeb6e4aa7d0b6281aacf0c70b59">263958bba46acbeb6e4aa7d0b6281aacf0c70b59</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462190785">EE Development Acceptance (master) - 174 - 2023-11-20[04:42:00]</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4512/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327940/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4512/jenkins-report.html">here</a>.</h5></details></html>

2023-11-20 19:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4512/">test-portal-acceptance-pullrequest(master)#4512</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4512/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/natocesarrego/liferay-portal/pull/1414">natocesarrego#1414</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462342546">[master] ci:test:hotel - TamyrisTorres &gt; natocesarrego - PR#1414 - 2023-11-20[10:01:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/9549/">publish-testray-report#9549</a><br/></div></div>

2023-11-21 12:04 UTC, closed without merging